services:
  - type: web
    name: chatbot-backend-educat
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
